create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    display_name varchar(160) not null,
    password_hash text not null,
    password_version bigint not null default 0,
    constraint app_user_username_not_blank check (length(trim(username)) > 0),
    constraint app_user_display_name_not_blank check (length(trim(display_name)) > 0),
    constraint app_user_password_version_nonnegative check (password_version >= 0)
);

create table calendar (
    id bigint generated by default as identity primary key,
    name varchar(160) not null,
    description varchar(4000),
    calendar_link_token char(11) not null unique,
    time_zone varchar(80) not null,
    public_access_enabled boolean not null,
    version integer not null default 0,
    constraint calendar_name_not_blank check (length(trim(name)) > 0),
    constraint calendar_description_length check (description is null or length(description) <= 4000),
    constraint calendar_link_token_canonical check (
        calendar_link_token ~ '^[A-Za-z0-9_-]{10}[AEIMQUYcgkosw048]$'
    ),
    constraint calendar_time_zone_not_blank check (length(trim(time_zone)) > 0),
    constraint calendar_version_nonnegative check (version >= 0)
);

create table calendar_membership (
    calendar_id bigint not null references calendar(id) on delete cascade,
    user_id bigint not null references app_user(id) on delete cascade,
    role_name varchar(20) not null,
    primary key (calendar_id, user_id),
    constraint calendar_membership_role check (role_name in ('EDITOR', 'ADMIN'))
);

create index calendar_membership_user_index
    on calendar_membership(user_id, calendar_id);

create table calendar_event (
    id bigint generated by default as identity primary key,
    calendar_id bigint not null references calendar(id) on delete cascade,
    title varchar(200) not null,
    description varchar(4000),
    location varchar(200),
    start_at timestamptz not null,
    end_at timestamptz not null,
    all_day boolean not null default false,
    version integer not null default 0,
    constraint calendar_event_title_not_blank check (length(trim(title)) > 0),
    constraint calendar_event_description_length check (description is null or length(description) <= 4000),
    constraint calendar_event_time_range check (end_at > start_at),
    constraint calendar_event_version_nonnegative check (version >= 0)
);

create index calendar_event_start_index
    on calendar_event(calendar_id, start_at, id);

create table invitation (
    id bigint generated by default as identity primary key,
    calendar_id bigint references calendar(id) on delete cascade,
    invitation_token varchar(80) not null unique,
    created_by_user_id bigint not null references app_user(id) on delete cascade,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    constraint invitation_token_canonical check (
        invitation_token ~ '^[A-Za-z0-9_-]{43}$'
    ),
    constraint invitation_lifetime check (
        expires_at > created_at and expires_at <= created_at + interval '7 days'
    )
);

create index invitation_creator_index
    on invitation(created_by_user_id, created_at desc);

create index invitation_calendar_index
    on invitation(calendar_id, created_at desc)
    where calendar_id is not null;

create table registration_bootstrap (
    singleton_id smallint primary key,
    consumed_at timestamptz,
    constraint registration_bootstrap_singleton check (singleton_id = 1)
);

insert into registration_bootstrap(singleton_id) values (1);
